a = int(input("write first num: "))
b = int(input("write second num: "))

print("сума:",a + b)
print("різниця:",a - b)
print("добуток:",a * b)
print("середнє арифметичне:",(a+b)/2)
print("середнє геометричне:",(a * b)**0.5)
print("відстань:",abs(a - b))
print("max:",max(a,b))
print("min:",min(a,b))
print("сума квадратів:",(a**2) + (b**2))
print("квадрат суми:",(a + b)**2)
print("a^b:",a**b)